# Form implementation generated from reading ui file 'choix_test.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(712, 547)
        MainWindow.setMinimumSize(QtCore.QSize(0, 60))
        
        self.ztest_verticalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.ztest_verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 711, 535))
        self.ztest_verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        
        self.ztest_vlTestTab = QtWidgets.QVBoxLayout(self.ztest_verticalLayoutWidget)
        self.ztest_vlTestTab.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.ztest_vlTestTab.setContentsMargins(0, 0, 0, 0)
        self.ztest_vlTestTab.setObjectName("vlTestTab")
        
        
        self.ztest_label_4 = QtWidgets.QLabel(self.ztest_verticalLayoutWidget)
        self.ztest_label_4.setText("")
        self.ztest_label_4.setObjectName("label_4")
        self.ztest_vlTestTab.addWidget(self.ztest_label_4)
        
        
        self.ztest_label = QtWidgets.QLabel("Inférence Statistique", self.ztest_verticalLayoutWidget)
        self.ztest_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(16)
        self.ztest_label.setFont(font)
        self.ztest_label.setStyleSheet("")
        self.ztest_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ztest_label.setObjectName("label")
        self.ztest_vlTestTab.addWidget(self.ztest_label)
        
        
        self.ztest_horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.ztest_horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.ztest_horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.ztest_cb_gp_test = QtWidgets.QComboBox(self.ztest_verticalLayoutWidget)
        self.ztest_cb_gp_test.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(12)
        self.ztest_cb_gp_test.setFont(font)
        self.ztest_cb_gp_test.setStyleSheet("")
        self.ztest_cb_gp_test.setObjectName("cb_gp_test")
        
        self.ztest_horizontalLayout_2.addWidget(self.ztest_cb_gp_test)
        self.ztest_vlTestTab.addLayout(self.ztest_horizontalLayout_2)
        
        self.ztest_horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.ztest_horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.ztest_horizontalLayout_6.setObjectName("horizontalLayout_6")
        
        self.ztest_sc_area_gp_test = QtWidgets.QScrollArea(self.ztest_verticalLayoutWidget)
        self.ztest_sc_area_gp_test.setMaximumSize(QtCore.QSize(600, 125))
        self.ztest_sc_area_gp_test.setWidgetResizable(True)
        self.ztest_sc_area_gp_test.setObjectName("sc_area_gp_test")
        
        self.ztest_scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.ztest_scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 598, 123))
        self.ztest_scrollAreaWidgetContents_3.setStyleSheet("m")
        self.ztest_scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.ztest_plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.ztest_scrollAreaWidgetContents_3)
        
        self.ztest_plainTextEdit_3.setGeometry(QtCore.QRect(0, 0, 600, 131))
        self.ztest_plainTextEdit_3.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(10)
        self.ztest_plainTextEdit_3.setFont(font)
        self.ztest_plainTextEdit_3.setObjectName("plainTextEdit_3")
        
        self.ztest_sc_area_gp_test.setWidget(self.ztest_scrollAreaWidgetContents_3)
        self.ztest_horizontalLayout_6.addWidget(self.ztest_sc_area_gp_test)
        self.ztest_vlTestTab.addLayout(self.ztest_horizontalLayout_6)
        
        self.ztest_label_2 = QtWidgets.QLabel("Text Statistique", self.ztest_verticalLayoutWidget)
        self.ztest_label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(16)
        self.ztest_label_2.setFont(font)
        self.ztest_label_2.setStyleSheet("margin-top:20")
        self.ztest_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ztest_label_2.setObjectName("label_2")
        self.ztest_vlTestTab.addWidget(self.ztest_label_2)
        
        self.ztest_horizontalLayout = QtWidgets.QHBoxLayout()
        self.ztest_horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.ztest_horizontalLayout.setObjectName("horizontalLayout")
        
        self.ztest_cb_test = QtWidgets.QComboBox(self.ztest_verticalLayoutWidget)
        self.ztest_cb_test.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(12)
        self.ztest_cb_test.setFont(font)
        self.ztest_cb_test.setStyleSheet("")
        self.ztest_cb_test.setObjectName("cb_test")
        self.ztest_horizontalLayout.addWidget(self.ztest_cb_test)
        self.ztest_vlTestTab.addLayout(self.ztest_horizontalLayout)
        
        self.ztest_horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.ztest_horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.ztest_horizontalLayout_4.setObjectName("horizontalLayout_4")
        
        self.ztest_sc_area_test = QtWidgets.QScrollArea(self.ztest_verticalLayoutWidget)
        self.ztest_sc_area_test.setMaximumSize(QtCore.QSize(600, 125))
        self.ztest_sc_area_test.setWidgetResizable(True)
        self.ztest_sc_area_test.setObjectName("sc_area_test")
        
        self.ztest_scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.ztest_scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 598, 123))
        self.ztest_scrollAreaWidgetContents_2.setStyleSheet("m")
        self.ztest_scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.ztest_plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.ztest_scrollAreaWidgetContents_2)
        
        self.ztest_plainTextEdit_2.setGeometry(QtCore.QRect(0, 0, 600, 131))
        self.ztest_plainTextEdit_2.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(10)
        self.ztest_plainTextEdit_2.setFont(font)
        self.ztest_plainTextEdit_2.setObjectName("plainTextEdit_2")
        
        self.ztest_sc_area_test.setWidget(self.ztest_scrollAreaWidgetContents_2)
        self.ztest_horizontalLayout_4.addWidget(self.ztest_sc_area_test)
        self.ztest_vlTestTab.addLayout(self.ztest_horizontalLayout_4)
        
        self.ztest_horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.ztest_horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.ztest_horizontalLayout_3.setObjectName("horizontalLayout_3")
        
        self.ztest_btn_test = QtWidgets.QPushButton("Allez au Test", self.ztest_verticalLayoutWidget)
        self.ztest_btn_test.setMinimumSize(QtCore.QSize(0, 55))
        self.ztest_btn_test.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(14)
        self.ztest_btn_test.setFont(font)
        self.ztest_btn_test.setStyleSheet("margin-top:20")
        self.ztest_btn_test.setObjectName("btn_test")
        self.ztest_horizontalLayout_3.addWidget(self.ztest_btn_test)
        
        self.ztest_vlTestTab.addLayout(self.ztest_horizontalLayout_3)
        self.ztest_label_3 = QtWidgets.QLabel(self.ztest_verticalLayoutWidget)
        self.ztest_label_3.setText("")
        self.ztest_label_3.setObjectName("label_3")
        self.ztest_vlTestTab.addWidget(self.ztest_label_3)
        
        
        MainWindow.setCentralWidget(self.ztest_verticalLayoutWidget)
        self.ztest_menubar = QtWidgets.QMenuBar(MainWindow)
        self.ztest_menubar.setGeometry(QtCore.QRect(0, 0, 712, 22))
        self.ztest_menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.ztest_menubar)
        self.ztest_statusbar = QtWidgets.QStatusBar(MainWindow)
        self.ztest_statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.ztest_statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ztest_label.setText(_translate("MainWindow", "Inférence Statistique"))
        self.ztest_label_2.setText(_translate("MainWindow", "Text Statistique"))
        self.ztest_btn_test.setText(_translate("MainWindow", "Allez au Test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
